In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
url="https://www.geeksforgeeks.org/districts-of-andhra-pradesh/"

In [ ]:
page=requests.get(url)

In [ ]:
soup=BeautifulSoup(page.text,'html')
print(soup)

In [ ]:
title=soup.find('title')
print(title)

<title>List of Districts of Andhra Pradesh: New Districts of AP Names</title>

In [ ]:
print(title.text)

List of Districts of Andhra Pradesh: New Districts of AP Names

In [ ]:
table = soup.find('table')
print(table)

<table><thead><tr><th style="text-align: justify"><b><strong>Name of District (With Code)</strong></b></th><th style="text-align: justify"><b><strong>Area (in sq.km.)</strong></b></th><th style="text-align: justify"><b><strong>Population (as per Census 2011)</strong></b></th></tr></thead><tbody><tr><th style="text-align: justify"><span>Srikakulam (SR)</span></th><td style="text-align: justify"><span>4,591</span></td><td style="text-align: justify"><span>21,91,471</span></td></tr><tr><th style="text-align: justify"><span>Parvathipuram Manyam (PM)</span></th><td style="text-align: justify"><span>3,659</span></td><td style="text-align: justify"><span>9,25,340</span></td></tr><tr><th style="text-align: justify"><span>Vizianagaram (VZ)</span></th><td style="text-align: justify"><span>4,122</span></td><td style="text-align: justify"><span>19,30,811</span></td></tr><tr><th style="text-align: justify"><span>Visakhapatnam (VS)</span></th><td style="text-align: justify"><span>1,048</span></td><td style="text-align: justify"><span>19,59,544</span></td></tr><tr><th style="text-align: justify"><span>Alluri Sitharama Raju (AS)</span></th><td style="text-align: justify"><span>12,251</span></td><td style="text-align: justify"><span>9,53,960</span></td></tr><tr><th style="text-align: justify"><span>Anakapalli (AK)</span></th><td style="text-align: justify"><span>4,292</span></td><td style="text-align: justify"><span>17,26,998</span></td></tr><tr><th style="text-align: justify"><span>Kakinada (KK)</span></th><td style="text-align: justify"><span>3,019</span></td><td style="text-align: justify"><span>20,92,374</span></td></tr><tr><th style="text-align: justify"><span>East Godavari (EG)</span></th><td style="text-align: justify"><span>2,561</span></td><td style="text-align: justify"><span>18,32,332</span></td></tr><tr><th style="text-align: justify"><span>Dr. B. R. Ambedkar Konaseema (KN)</span></th><td style="text-align: justify"><span>2,083</span></td><td style="text-align: justify"><span>17,19,093</span></td></tr><tr><th style="text-align: justify"><span>Eluru (EL)</span></th><td style="text-align: justify"><span>6,679</span></td><td style="text-align: justify"><span>20,71,700</span></td></tr><tr><th style="text-align: justify"><span>West Godavari (WG)</span></th><td style="text-align: justify"><span>2,178</span></td><td style="text-align: justify"><span>17,79,935</span></td></tr><tr><th style="text-align: justify"><span>NTR (NT)</span></th><td style="text-align: justify"><span>3,316</span></td><td style="text-align: justify"><span>22,18,591</span></td></tr><tr><th style="text-align: justify"><span>Krishna (KR)</span></th><td style="text-align: justify"><span>3,775</span></td><td style="text-align: justify"><span>17,35,079</span></td></tr><tr><th style="text-align: justify"><span>Palnadu (PL)</span></th><td style="text-align: justify"><span>7,298</span></td><td style="text-align: justify"><span>20,41,723</span></td></tr><tr><th style="text-align: justify"><span>Guntur (GU)</span></th><td style="text-align: justify"><span>2,443</span></td><td style="text-align: justify"><span>20,91,075</span></td></tr><tr><th style="text-align: justify"><span>Bapatla (BP)</span></th><td style="text-align: justify"><span>3,829</span></td><td style="text-align: justify"><span>15,86,918</span></td></tr><tr><th style="text-align: justify"><span>Prakasam (PR)</span></th><td style="text-align: justify"><span>14,322</span></td><td style="text-align: justify"><span>22,88,026</span></td></tr><tr><th style="text-align: justify"><span>Sri Potti Sriramulu Nellore (NE)</span></th><td style="text-align: justify"><span>10,441</span></td><td style="text-align: justify"><span>24,69,712</span></td></tr><tr><th style="text-align: justify"><span>Kurnool (KU)</span></th><td style="text-align: justify"><span>7,980</span></td><td style="text-align: justify"><span>22,71,686</span></td></tr><tr><th style="text-align: justify"><span>Nandyal (NN)</span></th><td style="text-align: justify"><span>9,682</span></td><td style="text-align: justify"><span>17,81,777</span></td></tr><tr><th style="text-align: justify"><span>Anantapur (AN)</span></th><td style="text-align: justify"><span>10,205</span></td><td style="text-align: justify"><span>22,41,105</span></td></tr><tr><th style="text-align: justify"><span>Sri Sathya Sai (SS)</span></th><td style="text-align: justify"><span>8,925</span></td><td style="text-align: justify"><span>18,40,043</span></td></tr><tr><th style="text-align: justify"><span>Kadapa (CU)</span></th><td style="text-align: justify"><span>11,228</span></td><td style="text-align: justify"><span>20,60,654</span></td></tr><tr><th style="text-align: justify"><span>Annamayya (AM)</span></th><td style="text-align: justify"><span>7,954</span></td><td style="text-align: justify"><span>16,97,308</span></td></tr><tr><th style="text-align: justify"><span>Tirupati (TR)</span></th><td style="text-align: justify"><span>8,231</span></td><td style="text-align: justify"><span>21,96,984</span></td></tr><tr><th style="text-align: justify"><span>Chittoor (CH)</span></th><td style="text-align: justify"><span>6,855</span></td><td style="text-align: justify"><span>18,72,951</span></td></tr></tbody></table>

In [ ]:
Headings = table.find_all('th')
print(Headings)

[<th style="text-align: justify"><b><strong>Name of District (With Code)</strong></b></th>, <th style="text-align: justify"><b><strong>Area (in sq.km.)</strong></b></th>, <th style="text-align: justify"><b><strong>Population (as per Census 2011)</strong></b></th>, <th style="text-align: justify"><span>Srikakulam (SR)</span></th>, <th style="text-align: justify"><span>Parvathipuram Manyam (PM)</span></th>, <th style="text-align: justify"><span>Vizianagaram (VZ)</span></th>, <th style="text-align: justify"><span>Visakhapatnam (VS)</span></th>, <th style="text-align: justify"><span>Alluri Sitharama Raju (AS)</span></th>, <th style="text-align: justify"><span>Anakapalli (AK)</span></th>, <th style="text-align: justify"><span>Kakinada (KK)</span></th>, <th style="text-align: justify"><span>East Godavari (EG)</span></th>, <th style="text-align: justify"><span>Dr. B. R. Ambedkar Konaseema (KN)</span></th>, <th style="text-align: justify"><span>Eluru (EL)</span></th>, <th style="text-align: justify"><span>West Godavari (WG)</span></th>, <th style="text-align: justify"><span>NTR (NT)</span></th>, <th style="text-align: justify"><span>Krishna (KR)</span></th>, <th style="text-align: justify"><span>Palnadu (PL)</span></th>, <th style="text-align: justify"><span>Guntur (GU)</span></th>, <th style="text-align: justify"><span>Bapatla (BP)</span></th>, <th style="text-align: justify"><span>Prakasam (PR)</span></th>, <th style="text-align: justify"><span>Sri Potti Sriramulu Nellore (NE)</span></th>, <th style="text-align: justify"><span>Kurnool (KU)</span></th>, <th style="text-align: justify"><span>Nandyal (NN)</span></th>, <th style="text-align: justify"><span>Anantapur (AN)</span></th>, <th style="text-align: justify"><span>Sri Sathya Sai (SS)</span></th>, <th style="text-align: justify"><span>Kadapa (CU)</span></th>, <th style="text-align: justify"><span>Annamayya (AM)</span></th>, <th style="text-align: justify"><span>Tirupati (TR)</span></th>, <th style="text-align: justify"><span>Chittoor (CH)</span></th>]

In [ ]:
Header = [i.text for i in Headings]
print(Header)

['Name of District (With Code)', 'Area (in sq.km.)', 'Population (as per Census 2011)', 'Srikakulam (SR)', 'Parvathipuram Manyam (PM)', 'Vizianagaram (VZ)', 'Visakhapatnam (VS)', 'Alluri Sitharama Raju (AS)', 'Anakapalli (AK)', 'Kakinada (KK)', 'East Godavari (EG)', 'Dr. B. R. Ambedkar Konaseema (KN)', 'Eluru (EL)', 'West Godavari (WG)', 'NTR (NT)', 'Krishna (KR)', 'Palnadu (PL)', 'Guntur (GU)', 'Bapatla (BP)', 'Prakasam (PR)', 'Sri Potti Sriramulu Nellore (NE)', 'Kurnool (KU)', 'Nandyal (NN)', 'Anantapur (AN)', 'Sri Sathya Sai (SS)', 'Kadapa (CU)', 'Annamayya (AM)', 'Tirupati (TR)', 'Chittoor (CH)']

In [ ]:
import pandas as pd
df = pd.DataFrame(columns = Header)
df

Empty DataFrame
Columns: [Name of District (With Code), Area (in sq.km.), Population (as per Census 2011), Srikakulam (SR), Parvathipuram Manyam (PM), Vizianagaram (VZ), Visakhapatnam (VS), Alluri Sitharama Raju (AS), Anakapalli (AK), Kakinada (KK), East Godavari (EG), Dr. B. R. Ambedkar Konaseema (KN), Eluru (EL), West Godavari (WG), NTR (NT), Krishna (KR), Palnadu (PL), Guntur (GU), Bapatla (BP), Prakasam (PR), Sri Potti Sriramulu Nellore (NE), Kurnool (KU), Nandyal (NN), Anantapur (AN), Sri Sathya Sai (SS), Kadapa (CU), Annamayya (AM), Tirupati (TR), Chittoor (CH)]
Index: []

[0 rows x 29 columns]

In [ ]:
rows = table.find_all('tr')
print(rows)

[<tr>
<th style="width: 16.8551%">River Name</th>
<th style="width: 21.48%">Length (Kilometers)</th>
<th style="width: 30.4214%">Source</th>
<th style="width: 71.223%">Mouth</th>
</tr>, <tr>
<td style="width: 16.8551%">Ganges (Ganga)</td>
<td style="width: 21.48%">2,525</td>
<td style="width: 30.4214%">Gangotri Glacier, Uttarakhand</td>
<td style="width: 71.223%">Bay of Bengal, West Bengal</td>
</tr>, <tr>
<td style="width: 16.8551%">Yamuna</td>
<td style="width: 21.48%">1,376</td>
<td style="width: 30.4214%">Yamunotri Glacier, Uttarakhand</td>
<td style="width: 71.223%">Ganges River, Allahabad, UP</td>
</tr>, <tr>
<td style="width: 16.8551%">Brahmaputra</td>
<td style="width: 21.48%">3,848</td>
<td style="width: 30.4214%">Tibet, China</td>
<td style="width: 71.223%">Bay of Bengal, Bangladesh</td>
</tr>, <tr>
<td style="width: 16.8551%">Indus</td>
<td style="width: 21.48%">3,180</td>
<td style="width: 30.4214%">Tibet, China</td>
<td style="width: 71.223%">Arabian Sea, Pakistan</td>
</tr>, <tr>
<td style="width: 16.8551%">Godavari</td>
<td style="width: 21.48%">1,465</td>
<td style="width: 30.4214%">Trimbak, Maharashtra</td>
<td style="width: 71.223%">Bay of Bengal, Andhra Pradesh</td>
</tr>, <tr>
<td style="width: 16.8551%">Krishna</td>
<td style="width: 21.48%">1,400</td>
<td style="width: 30.4214%">Mahabaleshwar, Maharashtra</td>
<td style="width: 71.223%">Bay of Bengal, Andhra Pradesh</td>
</tr>, <tr>
<td style="width: 16.8551%">Narmada</td>
<td style="width: 21.48%">1,312</td>
<td style="width: 30.4214%">Amarkantak, Madhya Pradesh</td>
<td style="width: 71.223%">Arabian Sea, Gujarat</td>
</tr>, <tr>
<td style="width: 16.8551%">Tapi</td>
<td style="width: 21.48%">724</td>
<td style="width: 30.4214%">Multai, Madhya Pradesh</td>
<td style="width: 71.223%">Arabian Sea, Gulf of Khambhat</td>
</tr>, <tr>
<td style="width: 16.8551%">Mahanadi</td>
<td style="width: 21.48%">858</td>
<td style="width: 30.4214%">Sihawa, Chhattisgarh</td>
<td style="width: 71.223%">Bay of Bengal, Odisha</td>
</tr>, <tr>
<td style="width: 16.8551%">Kaveri (Cauvery)</td>
<td style="width: 21.48%">800</td>
<td style="width: 30.4214%">Talakaveri, Karnataka</td>
<td style="width: 71.223%">Bay of Bengal, Tamil Nadu</td>
</tr>]

In [ ]:
ind=0
for i in rows[1:6]:
  row_data = i.find_all('td')
  every_row_data = [i.text for i in row_data]
  print(every_row_data)
  df.loc[ind] = every_row_data
  ind = ind+1

['Ganges (Ganga)', '2,525', 'Gangotri Glacier, Uttarakhand', 'Bay of Bengal, West Bengal']
['Yamuna', '1,376', 'Yamunotri Glacier, Uttarakhand', 'Ganges River, Allahabad, UP']
['Brahmaputra', '3,848', 'Tibet, China', 'Bay of Bengal, Bangladesh']
['Indus', '3,180', 'Tibet, China', 'Arabian Sea, Pakistan']
['Godavari', '1,465', 'Trimbak, Maharashtra', 'Bay of Bengal, Andhra Pradesh']

In [ ]:
df

,River Name,Length (Kilometers),Source,Mouth
0,Ganges (Ganga),"2,525","Gangotri Glacier, Uttarakhand","Bay of Bengal, West Bengal"
1,Yamuna,"1,376","Yamunotri Glacier, Uttarakhand","Ganges River, Allahabad, UP"
2,Brahmaputra,"3,848","Tibet, China","Bay of Bengal, Bangladesh"
3,Indus,"3,180","Tibet, China","Arabian Sea, Pakistan"
4,Godavari,"1,465","Trimbak, Maharashtra","Bay of Bengal, Andhra Pradesh"

In [ ]:
df.to_csv("states.csv")

In [ ]:
p = requests.get(url)

In [ ]:
code = BeautifulSoup(p.text,'html')
t = code.find('table')
print(t)

In [ ]:
data = t.find_all('td')
print(data)

[<td style="width: 16.8551%">Ganges (Ganga)</td>, <td style="width: 21.48%">2,525</td>, <td style="width: 30.4214%">Gangotri Glacier, Uttarakhand</td>, <td style="width: 71.223%">Bay of Bengal, West Bengal</td>, <td style="width: 16.8551%">Yamuna</td>, <td style="width: 21.48%">1,376</td>, <td style="width: 30.4214%">Yamunotri Glacier, Uttarakhand</td>, <td style="width: 71.223%">Ganges River, Allahabad, UP</td>, <td style="width: 16.8551%">Brahmaputra</td>, <td style="width: 21.48%">3,848</td>, <td style="width: 30.4214%">Tibet, China</td>, <td style="width: 71.223%">Bay of Bengal, Bangladesh</td>, <td style="width: 16.8551%">Indus</td>, <td style="width: 21.48%">3,180</td>, <td style="width: 30.4214%">Tibet, China</td>, <td style="width: 71.223%">Arabian Sea, Pakistan</td>, <td style="width: 16.8551%">Godavari</td>, <td style="width: 21.48%">1,465</td>, <td style="width: 30.4214%">Trimbak, Maharashtra</td>, <td style="width: 71.223%">Bay of Bengal, Andhra Pradesh</td>, <td style="width: 16.8551%">Krishna</td>, <td style="width: 21.48%">1,400</td>, <td style="width: 30.4214%">Mahabaleshwar, Maharashtra</td>, <td style="width: 71.223%">Bay of Bengal, Andhra Pradesh</td>, <td style="width: 16.8551%">Narmada</td>, <td style="width: 21.48%">1,312</td>, <td style="width: 30.4214%">Amarkantak, Madhya Pradesh</td>, <td style="width: 71.223%">Arabian Sea, Gujarat</td>, <td style="width: 16.8551%">Tapi</td>, <td style="width: 21.48%">724</td>, <td style="width: 30.4214%">Multai, Madhya Pradesh</td>, <td style="width: 71.223%">Arabian Sea, Gulf of Khambhat</td>, <td style="width: 16.8551%">Mahanadi</td>, <td style="width: 21.48%">858</td>, <td style="width: 30.4214%">Sihawa, Chhattisgarh</td>, <td style="width: 71.223%">Bay of Bengal, Odisha</td>, <td style="width: 16.8551%">Kaveri (Cauvery)</td>, <td style="width: 21.48%">800</td>, <td style="width: 30.4214%">Talakaveri, Karnataka</td>, <td style="width: 71.223%">Bay of Bengal, Tamil Nadu</td>]

In [ ]:
data_act = [i.text for i in data]
print(data_act)

['Ganges (Ganga)', '2,525', 'Gangotri Glacier, Uttarakhand', 'Bay of Bengal, West Bengal', 'Yamuna', '1,376', 'Yamunotri Glacier, Uttarakhand', 'Ganges River, Allahabad, UP', 'Brahmaputra', '3,848', 'Tibet, China', 'Bay of Bengal, Bangladesh', 'Indus', '3,180', 'Tibet, China', 'Arabian Sea, Pakistan', 'Godavari', '1,465', 'Trimbak, Maharashtra', 'Bay of Bengal, Andhra Pradesh', 'Krishna', '1,400', 'Mahabaleshwar, Maharashtra', 'Bay of Bengal, Andhra Pradesh', 'Narmada', '1,312', 'Amarkantak, Madhya Pradesh', 'Arabian Sea, Gujarat', 'Tapi', '724', 'Multai, Madhya Pradesh', 'Arabian Sea, Gulf of Khambhat', 'Mahanadi', '858', 'Sihawa, Chhattisgarh', 'Bay of Bengal, Odisha', 'Kaveri (Cauvery)', '800', 'Talakaveri, Karnataka', 'Bay of Bengal, Tamil Nadu']

In [ ]:
newdf= pd.DataFrame(columns = ['r_name','length','states','seas'])

In [ ]:
newdf

Empty DataFrame
Columns: [r_name, length, states, seas]
Index: []

In [ ]:
data_act[0:4]
print(len(data_act))

40

In [ ]:
ind = 0
st = 0
stop = 4
for i in data_act:
  if stop <= 40:
    newdf.loc[ind]= data_act[st:stop]
    st = st+4
    stop = stop+4
    ind = ind+1

In [ ]:
newdf

,r_name,length,states,seas
0,Ganges (Ganga),"2,525","Gangotri Glacier, Uttarakhand","Bay of Bengal, West Bengal"
1,Yamuna,"1,376","Yamunotri Glacier, Uttarakhand","Ganges River, Allahabad, UP"
2,Brahmaputra,"3,848","Tibet, China","Bay of Bengal, Bangladesh"
3,Indus,"3,180","Tibet, China","Arabian Sea, Pakistan"
4,Godavari,"1,465","Trimbak, Maharashtra","Bay of Bengal, Andhra Pradesh"
5,Krishna,"1,400","Mahabaleshwar, Maharashtra","Bay of Bengal, Andhra Pradesh"
6,Narmada,"1,312","Amarkantak, Madhya Pradesh","Arabian Sea, Gujarat"
7,Tapi,724,"Multai, Madhya Pradesh","Arabian Sea, Gulf of Khambhat"
8,Mahanadi,858,"Sihawa, Chhattisgarh","Bay of Bengal, Odisha"
9,Kaveri (Cauvery),800,"Talakaveri, Karnataka","Bay of Bengal, Tamil Nadu"